name: dashboard
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - scanpy
  - click
  - plotly
  - pyarrow
  - dash
  - pip
  - pip:
      - pycomfort
      - pyfunctional
      - more-itertools
      - primer3-py
      - git+https://github.com/MrTomRod/DnaFeaturesViewer
      - pyarrow
      - polars
      - genomepy
      - genotations>=0.1.3